<?php

namespace Container6qzBBsH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G2CB17RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g2CB17R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g2CB17R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'twigEnvironment' => ['services', '.container.private.twig', 'get_Container_Private_TwigService', false],
        ], [
            'twigEnvironment' => '?',
        ]);
    }
}
