<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6qzBBsH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6qzBBsH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6qzBBsH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6qzBBsH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6qzBBsH\App_KernelDevDebugContainer([
    'container.build_hash' => '6qzBBsH',
    'container.build_id' => 'a8e46752',
    'container.build_time' => 1638530783,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6qzBBsH');
